import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

import products from "../products.json"
import { checkout } from "../lib/checkout"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Shop</a>
        </h1>

        <ul className={styles.grid}>
          {products.map(({ title, description, price, image, id }) => (
            <li className={styles.card} key={title}>
              <a href="#">
                <img src={image} alt={title} />
                <h2>{title}</h2>
                <p>{price}</p>
                <p>{description}</p>
                <button
                  className={styles.button}
                  onClick={() =>
                    checkout({
                      lineItems: [
                        {
                          price: id,
                          quantity: 1,
                        },
                      ],
                    })
                  }
                >
                  Buy now!
                </button>
              </a>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
