import Head from "next/head";

import styles from "../styles/Home.module.css";

import products from "../products.json";
import { checkout } from "../lib/checkout";
import { useState } from "react";

type Product = {
  id: string;
  quantity: number;
};

const defaultState: { products: { [id: string]: Product } } = {
  products: {},
};

export default function Home() {
  const [cart, updateCart] = useState(defaultState);

  const cartItems = Object.keys(cart.products).map((key) => {
    const product = products.find(({ id }) => id === key);

    console.log(product);

    return {
      ...cart.products[key],
      pricePerItem: product?.price ?? 0,
    };
  });

  const subTotal = cartItems.reduce((acc, { pricePerItem, quantity }) => {
    return acc + pricePerItem * quantity;
  }, 0);

  const totalItems = cartItems.reduce((acc, { quantity }) => {
    return acc + quantity;
  }, 0);

  const addToCart = ({ id }: { id: string }) => {
    updateCart((prev) => {
      let cartState = { ...prev };
      if (cartState.products?.[id]) {
        cartState.products[id].quantity = cartState.products[id].quantity + 1;
      } else {
        cartState.products[id] = {
          id,
          quantity: 1,
        };
      }

      return cartState;
    });
  };

  const checkoutCart = () =>
    checkout({
      lineItems: cartItems.map((product) => ({
        price: product.id,
        quantity: product.quantity,
      })),
    });

  return (
    <div className={styles.container}>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to
          <img
            style={{ display: "block" }}
            src={"images/brl.svg"}
            alt={"logo"}
          />
          Shop
        </h1>

        <p className={styles.description}>
          <strong>Items:</strong>
          {totalItems}
          <br />
          <strong>Total cost:</strong>PLN {subTotal}
          <br />
          <button className={styles.button} onClick={checkoutCart}>
            Check out
          </button>
        </p>

        <ul className={styles.grid}>
          {products.map(({ title, description, price, image, id }) => (
            <li className={styles.card} key={title}>
              <a href="#">
                <img src={image} alt={title} />
                <h2>{title}</h2>
                <p>{price} pln</p>
                <p>{description}</p>
                <button
                  className={styles.button}
                  onClick={() => addToCart({ id })}
                >
                  Add to cart
                </button>
              </a>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>Helpers team</footer>
    </div>
  );
}
