import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

import products from "../products.json"
import { checkout } from "../lib/checkout"
import { useState } from "react"

type Product =  { 
  id: string,
  quantity: number
}

const defaultState: {products: {[id: string]: 
  Product
}} = {
  products:{}
} 

export default function Home() { 

  const [cart, updateCart] = useState(defaultState)

  const cartItems = Object.keys(cart.products).map(key=> {
    const product = products.find(({id})=> id === key )

    console.log(product)

    return { 
      ...cart.products[key],
      pricePerItem : product?.price ??0
    }

  })

  const subTotal = cartItems.reduce((acc, {pricePerItem,quantity})=>{
    return acc + (pricePerItem* quantity)


  },0)

  const totalItems = cartItems.reduce((acc, {quantity})=>{
    return acc + quantity


  },0)



  const addToCart = ({id}:{id:string})=> { 

    updateCart(prev=>{

      let cartState = {...prev}
      if(cartState.products?.[id]) {

        cartState.products[id].quantity = cartState.products[id].quantity + 1

      } else {
        cartState.products[id]= {
          id,
          quantity:1
        }
      } 

      return cartState

    })


  }


  const checkoutCart = ()=> 

  checkout({lineItems: cartItems.map(product=>({
    price: product.id,
    quantity: product.quantity
  }))})
    
  



  return (
    <div className={styles.container}>
       <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Shop</a>
        </h1>

        <p className={styles.description}>
          <strong>Items:</strong>{totalItems}
          <br/>
          <strong>Total cost:</strong>$ {subTotal}
          <br/>
          <button className={styles.button} onClick={checkoutCart}>Check out</button>



        </p>

        <ul className={styles.grid}>
          {products.map(({ title, description, price, image, id }) => (
            <li className={styles.card} key={title}>
              <a href="#">
                <img src={image} alt={title} />
                <h2>{title}</h2>
                <p>{price}</p>
                <p>{description}</p>
                <button
                  className={styles.button}
                  onClick={() => addToCart({id})
                   
                  }
                >Add to cart
                  
                </button>
              </a>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
